name: pre-release
run-name: Pre-release ${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
      tag:
        description: NPM tag
        required: true

jobs:
  release:
    if: ${{ github.repository == 'mistic100/Photo-Sphere-Viewer' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: ./.github/workflows/shared/setup
        with:
          turbo-cache: 'false'

      - name: build
        run: |
          yarn ci:version ${{ github.event.inputs.version }}
          yarn ci:build

      - name: npm publish
        run: |
          yarn ci:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_TAG: ${{ github.event.inputs.tag }}
